language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t vivek091195/docker-app -f Dockerfile.dev .

script:
  - docker run -e CI=true vivek091195/docker-app npm run test -- --coverage
