name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile.dev --tag vivek091195/docker-app

      - name: Run the tests
        run: docker run -e CI=true vivek091195/docker-app npm run test -- --coverage
